### ISSUE TITLE
exit with non-zero value when code is not formatted

### ISSUE THREAD

**Issue by x4m3** [jidicula/clang-format-action#1]
hi, thanks for the action, it works great.

just a question, do you know how i can make my job fail if a file is not formatted correctly?

i tried this but it doesn't seem to work:
```yml

  check-code:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run clang-format
      uses: jidicula/clang-format-action@master
    - name: The job has failed
      if: ${{ failure() }}
      run: echo "code is not clean"; exit 1
```

do you happen to know i could make that work?

thank you
