### ISSUE TITLE
Machine `ubuntu-latest` complaining about missing `clang-format-12`

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [jidicula/clang-format-action#118]
Since today I'm getting the following error from this action:
```
Run jidicula/clang-format-action@v4.3.0
  with:
    clang-format-version: 1[2](https://github.com/Luna-Scooters/Luna-One-CoreApp/actions/runs/3196082451/jobs/5217540648#step:4:2)
    check-path: lib
    fallback-style: llvm
Installing clang-format-12
E: Unable to locate package clang-format-12
/entrypoint.sh: line 22: /usr/bin/clang-format-12: No such file or directory

Failed on file: lib/Serial/include/ISerial.hpp
/entrypoint.sh: line 22: /usr/bin/clang-format-[12](https://github.com/Luna-Scooters/Luna-One-CoreApp/actions/runs/3196082451/jobs/5217540648#step:4:13): No such file or directory
```

But as far as I can see `ubuntu-latest` has `/usr/bin/clang-format-12` in that path.

Check below my full action:
```
name: clang-format Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'test'
          - 'lib'

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.3.0
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path }}
```

Are you aware of any change on `ubuntu-latest` which would break the compatibility with your action?
