### ISSUE TITLE
Add `-style file:<path>` option

### ISSUE THREAD

**Issue by mrousavy** [jidicula/clang-format-action#156]
Hey! Thanks for your package.

I'm trying to use it in a project where my code is in a subdirectory:

```
- .github/
- README.md
- package/
    - cpp/.clang-format
    - cpp/...
    - package.json
```

I couldn't figure out how to properly configure the github action to use the `.clang-format` file in that directory. Here's my workflow:

```yml
jobs:
  lint:
    name: Check clang-format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    strategy:
      matrix:
        path:
          - 'cpp'
          - 'android/src/main/cpp'
          - 'ios'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '16'
          check-path: ${{ matrix.path }}
          fallback-style: file:./package/cpp/.clang-format
```

Any thoughts?
