### ISSUE TITLE
Refactor task - use Ubuntu Mantic for `clang-format` versions 13 through 16

### ISSUE THREAD

**Issue by jidicula** [jidicula/clang-format-action#165]
[Ubuntu Mantic also contains `clang-format` versions 13 through 16](https://packages.ubuntu.com/search?suite=mantic&arch=any&searchon=names&keywords=clang-format). As much as possible, I prefer to reduce the number of Ubuntu versions I'm shipping in my Docker images. Switching versions 13 through 16 to Mantic would allow me to drop the Lunar dependency.

This task is fairly simple - in [these lines](https://github.com/jidicula/clang-format-action/blob/main/.github/workflows/clang-format-image.yml#L31-L34), switch the Ubuntu version to `mantic` to match [version 17](https://github.com/jidicula/clang-format-action/blob/main/.github/workflows/clang-format-image.yml#L30C1-L30C1).

**Comment by jidicula** [comment]
@Xav83 if you're looking for some more low-hanging fruit for Hacktoberfest, feel free to take a swing at this ☝️

**Comment by Ajeets6** [comment]
Hi,Can you assign this to me?

**Comment by jidicula** [comment]
Sure thing, thanks @Ajeets6 !

**Comment by danperkins** [comment]
@jidicula it seems like this image change wasn't entirely backwards compatible for our simple use case:
```
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "16"
```

Could you revert this change and then push it out again but with a new tag?  That at least gives people the ability to opt into it
