### ISSUE TITLE
Different Formatting Results Between Action and Locally

### ISSUE THREAD

**Issue by DeveloperPaul123** [jidicula/clang-format-action#198]
We are using `clang-format` 18 via LLVM `18.1.5` but after formatting the documents that the CI complains about in it's checks, no changes are applied. Is there something we're missing? Below is how we are using the action:

```yaml
- name: Check clang-format
    uses: jidicula/clang-format-action@v4.12.0
    with:
      clang-format-version: 18
      exclude-regex: '(3rdparty|libs|scripts|test|tests)'
```

**Comment by DeveloperPaul123** [comment]
We have a `.clang-format` and `.clang-format-ignore` in the root of the project.

**Comment by jidicula** [comment]
Interesting! Thanks for submitting this issue.


Have you noticed any overlap with the files it's complaining about in CI and your `.clang-format-ignore` file? Otherwise, my other suspicion would be that the `exclude-regex` is not correct.

Finally, is there a difference between the minor and/or patch versions of `clang-format` running in your CI as opposed to running locally? As of 0391c32fa54dcffc9d61e34f106433ab053c20fc (haven't included this in a release yet), I've added a `clang-format --version` output at the beginning of this action's execution. You can try this out by opening a PR in your repo with that workflow job step you included modified to:

```yaml
- name: Check clang-format
    uses: jidicula/clang-format-action@0391c32fa54dcffc9d61e34f106433ab053c20fc
    with:
      clang-format-version: 18
      exclude-regex: '(3rdparty|libs|scripts|test|tests)'
```
just to see what's output. If you do notice a difference in versions and you see a difference in behaviour, please leave a comment (and vote) in https://github.com/jidicula/clang-format-action/discussions/192.
