### ISSUE TITLE
Make it possible to use this action to run custom `clang-format` invocations

### ISSUE THREAD

**Issue by zyv** [jidicula/clang-format-action#235]
Hey there,

You've done a fantastic job providing all possible `clang-format` versions. However, at the moment the action insists on running `clang-format` itself.

It would be very nice if you could add a mode for it to behave more like `setup-*` actions, so that the requested `clang-format` is just put in the `$PATH` and it's our job to run it the way we want.

```yaml
- uses: jidicula/clang-format-action@v4
  with:
    clang-format-version: '13'
    setup-only: true
```

The reason I think this is desirable is that we have `clang-format` built into our build system (`make indent`) and I don't want to replicate that in your action settings.

However, setting up `clang-format` is challenging (as I'm sure you'll agree), so it would be great if I could reuse your work for our purposes.

Thanks a lot,
Yury
