### ISSUE TITLE
Ignore some files or directories?

### ISSUE THREAD

**Issue by micahsnyder** [jidicula/clang-format-action#35]
My library includes some vendored code and some generated code which we do not wish to reformat.  I know it's possible to use the `path` in a matrix to include specific directories. Eg: https://github.com/micahsnyder/clamav-devel/commit/a048ec1db706cdaaecbc5e35567f5cc788e438fa

But can I exclude specific files or subdirectories?

**Comment by jidicula** [comment]
I don't have an `exclude` input in this Action but it should be pretty straightforward to add. The file discovery happens in [this line](https://github.com/jidicula/clang-format-action/blob/94155adb7051b8d977f15e6e24b053c15d794619/entrypoint.sh#L53) of the Docker image's entrypoint script, so it would be a matter of

1. adding the input to `action.yml`
2. handing the input to the `find` command in `entrypoint.sh`

Some extra work would also have to be done to allow multiple paths to be passed to that input.

I can take a look this weekend, or if you want, you could submit a PR.

**Comment by micahsnyder** [comment]
Thanks for the quick reply @jidicula 

I tried to implement this using a regex: https://github.com/jidicula/clang-format-action/pull/36

I'm not sure that my implementation has the best user experience.  The `entrypoint.sh` script does seem to work for me, but I haven't tested it within an actual github action because I'm not familiar with how to test it.

I did also update the branch in my project for how I anticipate it will work there: https://github.com/micahsnyder/clamav-devel/blob/github-clang-format-action/.github/workflows/clang-format.yml

**Comment by jidicula** [comment]
Thanks @micahsnyder! I have a private test repo that I use for testing this action - I typically modify one of its workflows, so to test yours, I'll point towards the feature branch of your fork of this repo:

```yaml
name: clang-format Check
on:
  push:
  workflow_dispatch:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: micahsnyder/clang-format-action@exclude-regex
      with:
        check-path: 'c_test'
        clang_format_version: 11
        exclude-regex: 'capi'
```
