### ISSUE TITLE
clang-format 12 broken after last update

### ISSUE THREAD

**Issue by MCWertGaming** [jidicula/clang-format-action#48]
The clang-format 12 version of the workflow is broken after the last update:

This is the console output of the workflow
```bash
Installing clang-format-12
Get:1 http://security.ubuntu.com/ubuntu impish-security InRelease [90.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu impish InRelease [269 kB]
Get:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease [90.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease [90.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu impish/restricted amd64 Packages [119 kB]
Get:6 http://archive.ubuntu.com/ubuntu impish/main amd64 Packages [1809 kB]
Get:7 http://archive.ubuntu.com/ubuntu impish/universe amd64 Packages [16.7 MB]
Get:8 http://archive.ubuntu.com/ubuntu impish/multiverse amd64 Packages [255 kB]
Fetched 19.5 MB in 4s (5488 kB/s)
Reading package lists...
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
/entrypoint.sh: line 22: /usr/bin/clang-format-12: No such file or directory
Failed on file: frontend/tools.hpp
```

**Comment by MCWertGaming** [comment]
Same Problem with clang-format 13
```bash
Installing clang-format-13
Get:1 http://security.ubuntu.com/ubuntu impish-security InRelease [90.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu impish InRelease [269 kB]
Get:3 http://archive.ubuntu.com/ubuntu impish-updates InRelease [90.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu impish-backports InRelease [90.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu impish/restricted amd64 Packages [119 kB]
Get:6 http://archive.ubuntu.com/ubuntu impish/main amd64 Packages [1809 kB]
Get:7 http://archive.ubuntu.com/ubuntu impish/multiverse amd64 Packages [255 kB]
Get:8 http://archive.ubuntu.com/ubuntu impish/universe amd64 Packages [16.7 MB]
Fetched 19.5 MB in 2s (8454 kB/s)
Reading package lists...
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
/entrypoint.sh: line 22: /usr/bin/clang-format-13: No such file or directory
Failed on file: frontend/tools.hpp
```

My workflow configuration:

```yml
name: clang-format Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format in the frontends folder
      uses: jidicula/clang-format-action@v4.1.0
      with:
        clang-format-version: '13' # <- Tried both 12 and 13
        check-path: 'frontend'
```
